routes/web.php
<?php
Route::get('test','Controller@test');

Route::group(['middleware' => 'CheckKeToan'],function(){

	Route::group(['prefix' => 'muc_luong', 'as' => 'muc_luong.'],function(){
		Route::get('','LuongController@view_all')->name('view_all');
		Route::get('view_insert','LuongController@view_insert')->name('view_insert');
		Route::post('process_insert','LuongController@process_insert')->name('process_insert');


		Route::get('view_update/{ma_muc_luong}','LuongController@view_update')->name('view_update');
		Route::post('process_update/{ma_muc_luong}','LuongController@process_update')->name('process_update');
	});
	?>

	<?php

	Route::group(['prefix' => 'ke_toan', 'as' => 'ke_toan.'],function(){
		Route::get('','Ke_toanController@view_all')->name('view_all_ke_toan');
		Route::get('view_insert','Ke_toanController@view_insert')->name('view_insert_ke_toan');
		Route::post('process_insert','Ke_toanController@process_insert')->name('process_insert');

		Route::get('view_update/{ma_ke_toan}','Ke_toanController@view_update')->name('view_update_ke_toan');
		Route::post('process_update/{ma_ke_toan}','Ke_toanController@process_update')->name('process_update');
	});

});

Route::group(['middleware' => 'CheckGiaoVien'],function(){

	Route::group(['prefix' => 'giao_vien', 'as' => 'giao_vien.'],function(){
		Route::get('','GiaoVienController@view_all')->name('view_all');
		Route::get('view_insert','GiaoVienController@view_insert')->name('view_insert');
		Route::post('process_insert','GiaoVienController@process_insert')->name('process_insert');


		Route::get('view_update/{ma_giao_vien}','GiaoVienController@view_update')->name('view_update');
		Route::post('process_update/{ma_giao_vien}','GiaoVienController@process_update')->name('process_update');
	});	



	Route::group(['prefix' => 'cham_cong', 'as' => 'cham_cong.'],function(){
		Route::get('','ChamCongController@view_all')->name('view_all');
		Route::get('view_insert','ChamCongController@view_insert')->name('view_insert');
		Route::post('process_insert','ChamCongController@process_insert')->name('process_insert');


		Route::get('view_update/{ngay}','GiaoVienController@view_update')->name('view_update');
		Route::post('process_update/{ngay}','GiaoVienController@process_update')->name('process_update');
	});	
});

Route::get('login','Controller@login')->name('view_login');
Route::post('process_login','Controller@process_login')->name('process_login');

Route::get('logout','Controller@logout')->name('logout');
?>

app/Http/Controllers/ChamCongController.php
<?php

namespace App\Http\Controllers;

use App\Model\ChamCongModel;
use Illuminate\Http\Request;

class ChamCongController
{
	function view_all(){
		$array = ChamCongModel::get_all();
		return view('cham_cong.view_all',compact('array'));
	}
	function view_insert(){
		return view('cham_cong.view_insert');
	}
	function process_insert(Request $rq){
		$cham_cong = new ChamCongModel();
		$cham_cong->ngay = $rq->get('ngay');
		$cham_cong->ma_giao_vien = $rq->get('ma_giao_vien');
		$cham_cong->so_gio_day = $rq->get('so_gio_day');
		
		$cham_cong->insert();

		return redirect()->route('cham_cong.view_all');
	}
}

resources/views/cham_cong/view_all.blade.php
@extends('layer.master')
@section('body')
<body>
<a href="{{ route('cham_cong.view_insert') }}">
	Chấm công
</a>
<table border="1" width="100%">
	<tr>
		<th>Ngày</th>
		<th>Mã giáo viên</th>
		<th>Số giờ dạy</th>
		
	</tr>
	@foreach ($array as $each)
		<tr>
			<td>{{$each->ngay}}</td>

			<td>{{$each->ma_giao_vien}}</td>
			<td>{{$each->so_gio_day}}</td>

		</tr>
	@endforeach
</table>
</body>
@endsection

resources/views/cham_cong/view_insert.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form action="{{ route('cham_cong.process_insert')}}" method="post">
	{{csrf_field()}}
	Ngày
	<input type="date" name="ngay">
	<br>
	Mã giáo viên
	<input type="text" name="ma_giao_vien">
	<br>
	Số giờ dạy
	<input type="text" name="so_gio_day">
	
	<br>
	<button>Chấm công</button>
</form>
</body>
</html>

resources/views/cham_cong/view_update.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
</head>
<body>
<form action="{{ route('cham_cong.process_update',['ngay'=> $each->ngay]) }}" method="post">
	{{csrf_field()}}
	Mã giáo viên
	<input type="text" name="ma_giao_vien" value="{{$each->ma_giao_vien}}">
	<br>
	Số giờ dạy
	<input type="text" name="so_gio_day" value="{{$each->so_gio_day}}">
	<button>OK</button>
</form>
</body>
</html>